[package]
name="appy"
version="0.1.0"
edition="2021"

[lib]
name="appy"
path="src/lib.rs"

[dependencies]
appy-macros = {path="./appy-macros"}
gl = "0.14.0"
nalgebra-glm = "0.18.0"
sdl2 = "0.35.2"
rusttype = {version="0.9.3", features=["gpu_cache"]}
android_log-sys = "0.3.0"

#glutin = "0.30.7"
#winit = "0.28.3"
#glutin-winit = "0.3.0"
#raw-window-handle = "0.5.2"

[target.'cfg(target_os="android")'.dependencies]
android_log-sys = "0.3.0"
