[package]
name="appy"
version="0.1.0"
edition="2021"

[lib]
name="appy"
path="src/lib.rs"

[[bin]]
name="appy"
path="src/cl/bin.rs"

[dependencies]

# lib deps
appy-macros = {path="./appy-macros"}
gl = "0.14.0"
nalgebra-glm = "0.18.0"
sdl2 = "0.35.2"
rusttype = {version="0.9.3", features=["gpu_cache"]}
android_log-sys = "0.3.0"

# bin deps
toml = "0.7.3"
fs_extra = "1.3.0"
symlink = "0.1.0"

[target.'cfg(target_os="android")'.dependencies]
android_log-sys = "0.3.0"
