[package]
name="appy-macros"
version="0.1.0"
edition="2021"

[lib]
proc-macro=true

[dependencies]
proc-macro2 = "1.0.52"
quote = "1.0.26"
syn = { version = "1", features = ["full"] }
syn-rsx = "0.9.0"
