[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[package.metadata]
appid="dev.wayan.calc"

[lib]
name="main"
path="src/main.rs"
crate-type=["cdylib"]

[dependencies]
appy = {path="../.."}
