[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[package.metadata]
appid="com.example.hello"

[lib]
name="main"
path="src/main.rs"
crate-type=["cdylib"]

[dependencies]
appy = {path="../.."}
