[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[package.metadata]
appid="com.example.hello"
appname="Hello Appy"

[lib]
path="src/main.rs"
crate-type=["cdylib"]

[dependencies]
appy = {path="../..",features=["sdl"]}
#appy = {path="../..",features=["glutin"]}
