[package]
name="appy"
version="0.1.0"
edition="2021"

[dependencies]
appy-macros = {path="../appy-macros"}
gl = "0.14.0"
nalgebra-glm = "0.18.0"
sdl2 = "0.35.2"
rusttype = {version="0.9.3", features=["gpu_cache"]}
